# Generated by Django 4.2.6 on 2023-10-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Меню'},
        ),
    ]
